network_config:
{% for int in network_interfaces %}
{% set _int = network_interfaces[int] %}
{% if  _int['type'] is defined %}
{% if  (_int['type'] == 'linux_bond' or _int['type'] == 'ovs_bond') %}
  - type: {{ _int['type'] }}
    name: {{ int }}
    use_dhcp: false
    members:
{% for bonding_member in _int['member'] %}
      - type: interface
        name: {{ bonding_member }}
        mtu: {{ _int['mtu'] | default('1500') }}
{% endfor %}
    bonding_options: {{ _int['bonding_options'] }}
{% elif  (_int['type'] == 'vlan')  %}
  - type: {{ _int['type'] }}
    use_dhcp: false
    device: {{ _int['physdev'] }}
    vlan_id: {{ _int['vlanid'] }}
{% endif %}
{% else %}
  - type: {{ _int['type'] | default('interface') }}
    name: {{ int }}
    use_dhcp: false
{% endif %}
{% if  _int['ipaddr'] is defined %}
    addresses:
      - ip_netmask: {{ _int['ipaddr'] }}/{{ _int['netmask'] | default('24') }}
{% endif %}
    nm_controlled: false
    mtu: {{ _int['mtu'] | default('1500') }}
{% if  _int['gateway'] is defined %}
    routes:
      - ip_netmask: 0.0.0.0/0
        next_hop: {{ _int['gateway'] }}
{% endif %}
{% endfor %}
